### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by FlorianHendrickx** [yin/apify-yelp#10]
I tried running this crawler and get this error with the default settings:

2020-07-31T10:34:45.999Z ERROR: BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.yelp.com/biz/the-mayfair-chippy-london-2?osq=Restaurant","retryCount":1,"id":"63xbVU2LhoTkqVT"}
2020-07-31T10:34:46.000Z   TypeError: Cannot read property 'attribs' of undefined
2020-07-31T10:34:46.000Z     at Object.yelpBusinessInfo (/home/myuser/src/extractors.js:31:63)
2020-07-31T10:34:46.001Z     at CheerioCrawler.handlePageFunction (/home/myuser/src/scrapers.js:57:42)
2020-07-31T10:34:46.002Z     at CheerioCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/cheerio_crawler.js:434:50)
2020-07-31T10:34:46.002Z     at runMicrotasks (<anonymous>)
2020-07-31T10:34:46.003Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-31T10:34:46.004Z     at async /home/myuser/node_modules/apify/build/utils.js:411:20

**Comment by pocesar** [comment]
hey @FlorianHendrickx thanks for the report, it is indeed not working as expected.

**Comment by pocesar** [comment]
this has been fixed. please try again @FlorianHendrickx
